INSERT INTO products (productName, productDescription, price, inStock) VALUES
('Wireless Bluetooth Headphones', 'Premium noise-cancelling headphones with 30-hour battery life and comfortable over-ear design.', 129.99, 45),
('Ergonomic Office Chair', 'Adjustable office chair with lumbar support, breathable mesh back, and 360-degree swivel.', 199.95, 12),
('Stainless Steel Water Bottle', 'Vacuum-insulated 24oz bottle that keeps drinks cold for 24 hours or hot for 12 hours.', 34.50, 78),
('Smart LED Desk Lamp', 'Touch-sensitive lamp with adjustable brightness, color temperature settings, and USB charging port.', 49.99, 23),
('Portable Power Bank', 'High-capacity 20000mAh power bank with fast charging and dual USB ports for multiple devices.', 45.99, 56),
('Cast Iron Skillet', '10-inch pre-seasoned cast iron skillet, perfect for stovetop, oven, and campfire cooking.', 29.95, 31),
('Yoga Mat', 'Eco-friendly non-slip yoga mat with alignment marks, 6mm thickness for joint protection.', 38.50, 64),
('Mechanical Keyboard', 'Tactile mechanical keyboard with customizable RGB lighting and programmable macro keys.', 89.99, 18),
('Air Purifier', 'HEPA air purifier that removes 99.97% of airborne particles, ideal for rooms up to 500 sq ft.', 149.95, 9),
('Coffee Grinder', 'Burr coffee grinder with 18 grind settings for precision brewing from espresso to French press.', 69.99, 27),
('Wireless Charging Pad', 'Fast-charging Qi-compatible wireless charger with non-slip surface and sleek design.', 24.95, 42),
('External SSD', '1TB high-speed external SSD with USB-C connectivity and durable aluminum casing.', 159.99, 15),
('Hiking Backpack', 'Waterproof 45L hiking backpack with hydration sleeve, multiple compartments, and padded straps.', 79.95, 21),
('Digital Food Scale', 'Precision kitchen scale with tare function and multiple unit options including grams and ounces.', 19.99, 38),
('Smart Indoor Garden', 'Automated hydroponic garden system with built-in grow lights for year-round fresh herbs.', 129.95, 7),
('Fitness Tracker', 'Waterproof fitness band with heart rate monitoring, sleep tracking, and 7-day battery life.', 59.99, 33),
('Insulated Travel Mug', 'Leakproof 16oz travel mug that maintains temperature for hours with one-handed operation lid.', 27.50, 51),
('Bamboo Cutting Board', 'Sustainable bamboo cutting board with juice groove and non-slip feet, measures 18 by 12 inches.', 32.95, 19),
('Compact Blender', 'Personal blender with 600W motor, BPA-free 20oz travel bottle, and one-touch operation.', 44.99, 25),
('WiFi Range Extender', 'Dual-band WiFi extender that eliminates dead zones and supports up to 25 connected devices.', 39.95, 29);